---
- name: Make time right

  hosts: localhost
  tasks: #tasks - 2 tasks in this playbook 

 - name: Make sure the package is installed
   package: #module 1
	   name: ntpd
	   state: present

 - name: Make sure that service is started
   services: #module 2
	  name: ntpd
	  state: started
